bounty_application_ratios = {
    npc_creep_melee                 =  12,
    npc_creep_ranged                =   9,

    npc_jungle_small_shroom         =   4,
    npc_jungle_big_shroom           =  38,
    npc_jungle_cute_shroom          =  75,

    npc_jungle_small_ugger          =  19,
    npc_jungle_big_ugger            =  58,
    npc_jungle_ugly_ugger           =  75,

    npc_jungle_small_fish           =  19,
    npc_jungle_big_fish             =  58,
    npc_jungle_ugly_fish            =  75,

    npc_jungle_big_boar             =  110,
    npc_jungle_small_boar           =  52,

    npc_well_worker                 =   6,
}
bounty_application_ratios_nearby = {
    npc_creep_melee                 =  10,
    npc_creep_ranged                =   7,

    npc_jungle_small_shroom         =   0,
    npc_jungle_big_shroom           =   0,
    npc_jungle_cute_shroom          =   0,

    npc_jungle_small_ugger          =   0,
    npc_jungle_big_ugger            =   0,
    npc_jungle_ugly_ugger           =   0,

    npc_jungle_small_fish           =   0,
    npc_jungle_big_fish             =   0,
    npc_jungle_ugly_fish            =   0,

    npc_jungle_big_boar             =   0,
    npc_jungle_small_boar           =   0,

    npc_well_worker                 =   0,
}
haste_cooldown_application_ratios = {
	npc_dota_hero_axe 				= 0.60, -- Warden
	npc_dota_hero_crystal_maiden  	= 0.60, -- Winter's Bride
	npc_dota_hero_earth_spirit 		= 0.60, -- Sculptor
	npc_dota_hero_templar_assassin 	= 0.15, -- Merchant Princess
    npc_dota_hero_naga_siren        = 0.60, -- The Typhoon
    npc_dota_hero_skeleton_king     = 0.20, -- Warlock Knight
    npc_dota_hero_rattletrap        = 0.60, -- Ancient Babysitter
    npc_dota_hero_spectre           = 0.60, -- Art Prodigy
    npc_dota_hero_legion_commander  = 0.15, -- High Huntress
    npc_dota_hero_lycan             = 0.60, -- The Alpha
    npc_dota_hero_bloodseeker       = 0.20, -- Survivor
    npc_dota_hero_undying           = 0.50, -- Rotting Tomb
    npc_dota_hero_pudge             = 0.50, -- Desert Raider
    npc_dota_hero_vengefulspirit    = 0.50, -- Elegant Dancer
    npc_dota_hero_beastmaster       = 0.60, -- Enforcer
    npc_dota_hero_meepo             = 0.60, -- Tangled Dreamer
    npc_dota_hero_oracle            = 0.60, -- Loremaster
    npc_dota_hero_life_stealer      = 0.15, -- Flesh
    npc_dota_hero_ember_spirit      = 0.60, -- Pyrebug
    npc_dota_hero_invoker           = 0.60, -- Mad King
    npc_dota_hero_queenofpain       = 0.60, -- Purifier
    npc_dota_hero_phantom_assassin  = 0.60, -- Noble Shadow
    npc_dota_hero_spirit_breaker    = 0.50, -- Shepherd
    npc_dota_hero_slark             = 0.60, -- Whale Hunter
}
haste_attack_speed_application_ratios = {
	npc_dota_hero_axe 				= 0.60, -- Warden
	npc_dota_hero_crystal_maiden  	= 0.20, -- Winter's Bride
	npc_dota_hero_earth_spirit 		= 0.30, -- Sculptor
	npc_dota_hero_templar_assassin 	= 1.00, -- Merchant Princess
    npc_dota_hero_naga_siren        = 0.20, -- The Typhoon
    npc_dota_hero_skeleton_king     = 0.20, -- Warlock Knight
    npc_dota_hero_rattletrap        = 0.30, -- Ancient Babysitter
    npc_dota_hero_spectre           = 0.20, -- Art Prodigy
    npc_dota_hero_legion_commander  = 1.00, -- High Huntress
    npc_dota_hero_lycan             = 0.20, -- The Alpha
    npc_dota_hero_bloodseeker       = 1.00, -- Survivor
    npc_dota_hero_undying           = 0.50, -- Rotting Tomb
    npc_dota_hero_pudge             = 0.50, -- Desert Raider
    npc_dota_hero_vengefulspirit    = 0.50, -- Elegant Dancer
    npc_dota_hero_beastmaster       = 0.60, -- Enforcer
    npc_dota_hero_meepo             = 0.20, -- Tangled Dreamer
    npc_dota_hero_oracle            = 0.20, -- Loremaster
    npc_dota_hero_life_stealer      = 1.00, -- Flesh
    npc_dota_hero_ember_spirit      = 0.20, -- Pyrebug
    npc_dota_hero_invoker           = 0.20, -- Mad King
    npc_dota_hero_queenofpain       = 0.20, -- Purifier
    npc_dota_hero_phantom_assassin  = 0.30, -- Noble Shadow
    npc_dota_hero_spirit_breaker    = 0.50, -- Shepherd
    npc_dota_hero_slark             = 0.30, -- Whale Hunter
}
power_attack_damage_application_ratios = {
	npc_dota_hero_axe 				= 1.00, -- Warden
	npc_dota_hero_crystal_maiden  	= 0.20, -- Winter's Bride
	npc_dota_hero_earth_spirit 		= 0.80, -- Sculptor
	npc_dota_hero_templar_assassin 	= 1.00, -- Merchant Princess
    npc_dota_hero_naga_siren        = 0.20, -- The Typhoon
    npc_dota_hero_skeleton_king     = 1.00, -- Warlock Knight
    npc_dota_hero_rattletrap        = 0.30, -- Ancient Babysitter
    npc_dota_hero_spectre           = 0.20, -- Art Prodigy
    npc_dota_hero_legion_commander  = 1.00, -- High Huntress
    npc_dota_hero_lycan             = 0.20, -- The Alpha
    npc_dota_hero_bloodseeker       = 1.00, -- Survivor
    npc_dota_hero_undying           = 0.80, -- Rotting Tomb
    npc_dota_hero_pudge             = 0.80, -- Desert Raider
    npc_dota_hero_vengefulspirit    = 0.80, -- Elegant Dancer
    npc_dota_hero_beastmaster       = 1.00, -- Enforcer
    npc_dota_hero_meepo             = 0.20, -- Tangled Dreamer
    npc_dota_hero_oracle            = 0.20, -- Loremaster
    npc_dota_hero_life_stealer      = 1.00, -- Flesh
    npc_dota_hero_ember_spirit      = 0.30, -- Pyrebug
    npc_dota_hero_invoker           = 0.20, -- Mad King
    npc_dota_hero_queenofpain       = 0.20, -- Purifier
    npc_dota_hero_phantom_assassin  = 0.30, -- Noble Shadow
    npc_dota_hero_spirit_breaker    = 0.80, -- Shepherd
    npc_dota_hero_slark             = 0.30, -- Whale Hunter
}
level_health_application_ratios = {
	npc_dota_hero_axe 				= 77.0, -- Warden
	npc_dota_hero_crystal_maiden  	= 67.0, -- Winter's Bride
	npc_dota_hero_earth_spirit 		= 83.0, -- Sculptor
	npc_dota_hero_templar_assassin 	= 77.0, -- Merchant Princess
    npc_dota_hero_naga_siren        = 67.0, -- The Typhoon
    npc_dota_hero_skeleton_king     = 78.0, -- Warlock Knight
    npc_dota_hero_rattletrap        = 78.0, -- Ancient Babysitter
    npc_dota_hero_spectre           = 65.0, -- Art Prodigy
    npc_dota_hero_legion_commander  = 77.0, -- High Huntress
    npc_dota_hero_lycan             = 67.0, -- The Alpha
    npc_dota_hero_bloodseeker       = 80.0, -- Survivor
    npc_dota_hero_undying           = 78.0, -- Rotting Tomb
    npc_dota_hero_pudge             = 78.0, -- Desert Raider
    npc_dota_hero_vengefulspirit    = 67.0, -- Elegant Dancer
    npc_dota_hero_beastmaster       = 77.0, -- Enforcer
    npc_dota_hero_meepo             = 65.0, -- Tangled Dreamer
    npc_dota_hero_oracle            = 67.0, -- Loremaster
    npc_dota_hero_life_stealer      = 77.0, -- Flesh
    npc_dota_hero_ember_spirit      = 78.0, -- Pyrebug
    npc_dota_hero_invoker           = 67.0, -- Mad King
    npc_dota_hero_queenofpain       = 65.0, -- Purifier
    npc_dota_hero_phantom_assassin  = 78.0, -- Noble Shadow
    npc_dota_hero_spirit_breaker    = 78.0, -- Shepherd
    npc_dota_hero_slark             = 78.0, -- Whale Hunter
}
level_health_regen_application_ratios = {   -- These values are in hp regen / 5 seconds
	npc_dota_hero_axe 				= 0.65, -- Warden
	npc_dota_hero_crystal_maiden  	= 0.45, -- Winter's Bride
	npc_dota_hero_earth_spirit 		= 0.85, -- Sculptor
	npc_dota_hero_templar_assassin 	= 0.60, -- Merchant Princess
    npc_dota_hero_naga_siren        = 0.45, -- The Typhoon
    npc_dota_hero_skeleton_king     = 0.50, -- Warlock Knight
    npc_dota_hero_rattletrap        = 0.60, -- Ancient Babysitter
    npc_dota_hero_spectre           = 0.50, -- Art Prodigy
    npc_dota_hero_legion_commander  = 0.60, -- High Huntress
    npc_dota_hero_lycan             = 0.45, -- The Alpha
    npc_dota_hero_bloodseeker       = 0.85, -- Survivor
    npc_dota_hero_undying           = 0.55, -- Rotting Tomb
    npc_dota_hero_pudge             = 0.75, -- Desert Raider
    npc_dota_hero_vengefulspirit    = 0.45, -- Elegant Dancer
    npc_dota_hero_beastmaster       = 0.65, -- Enforcer
    npc_dota_hero_meepo             = 0.50, -- Tangled Dreamer
    npc_dota_hero_oracle            = 0.45, -- Loremaster
    npc_dota_hero_life_stealer      = 0.60, -- Flesh
    npc_dota_hero_ember_spirit      = 0.55, -- Pyrebug
    npc_dota_hero_invoker           = 0.45, -- Mad King
    npc_dota_hero_queenofpain       = 0.50, -- Purifier
    npc_dota_hero_phantom_assassin  = 0.60, -- Noble Shadow
    npc_dota_hero_spirit_breaker    = 0.75, -- Shepherd
    npc_dota_hero_slark             = 0.60, -- Whale Hunter
}
level_attack_damage_application_ratios = {
	npc_dota_hero_axe 				= 2.40, -- Warden
	npc_dota_hero_crystal_maiden  	= 2.80, -- Winter's Bride
	npc_dota_hero_earth_spirit 		= 2.70, -- Sculptor
	npc_dota_hero_templar_assassin 	= 2.20, -- Merchant Princess
    npc_dota_hero_naga_siren        = 2.80, -- The Typhoon
    npc_dota_hero_skeleton_king     = 2.70, -- Warlock Knight
    npc_dota_hero_rattletrap        = 2.60, -- Ancient Babysitter
    npc_dota_hero_spectre           = 2.70, -- Art Prodigy
    npc_dota_hero_legion_commander  = 2.20, -- High Huntress
    npc_dota_hero_lycan             = 2.80, -- The Alpha
    npc_dota_hero_bloodseeker       = 2.70, -- Survivor
    npc_dota_hero_undying           = 2.85, -- Rotting Tomb
    npc_dota_hero_pudge             = 2.80, -- Desert Raider
    npc_dota_hero_vengefulspirit    = 2.80, -- Elegant Dancer
    npc_dota_hero_beastmaster       = 2.40, -- Enforcer
    npc_dota_hero_meepo             = 2.70, -- Tangled Dreamer
    npc_dota_hero_oracle            = 2.80, -- Loremaster
    npc_dota_hero_life_stealer      = 2.20, -- Flesh
    npc_dota_hero_ember_spirit      = 2.70, -- Pyrebug
    npc_dota_hero_invoker           = 2.80, -- Mad King
    npc_dota_hero_queenofpain       = 2.70, -- Purifier
    npc_dota_hero_phantom_assassin  = 2.60, -- Noble Shadow
    npc_dota_hero_spirit_breaker    = 2.80, -- Shepherd
    npc_dota_hero_slark             = 2.60, -- Whale Hunter
}
level_attack_speed_application_ratios = {
	npc_dota_hero_axe 				= 3.10, -- Warden
	npc_dota_hero_crystal_maiden  	= 1.60, -- Winter's Bride
	npc_dota_hero_earth_spirit 		= 2.60, -- Sculptor
	npc_dota_hero_templar_assassin 	= 2.40, -- Merchant Princess
    npc_dota_hero_naga_siren        = 1.60, -- The Typhoon
    npc_dota_hero_skeleton_king     = 3.00, -- Warlock Knight
    npc_dota_hero_rattletrap        = 2.60, -- Ancient Babysitter
    npc_dota_hero_spectre           = 2.00, -- Art Prodigy
    npc_dota_hero_legion_commander  = 2.40, -- High Huntress
    npc_dota_hero_lycan             = 1.60, -- The Alpha
    npc_dota_hero_bloodseeker       = 2.50, -- Survivor
    npc_dota_hero_undying           = 1.50, -- Rotting Tomb
    npc_dota_hero_pudge             = 2.40, -- Desert Raider
    npc_dota_hero_vengefulspirit    = 1.60, -- Elegant Dancer
    npc_dota_hero_beastmaster       = 3.10, -- Enforcer
    npc_dota_hero_meepo             = 2.00, -- Tangled Dreamer
    npc_dota_hero_oracle            = 1.60, -- Loremaster
    npc_dota_hero_life_stealer      = 2.40, -- Flesh
    npc_dota_hero_ember_spirit      = 1.60, -- Pyrebug
    npc_dota_hero_invoker           = 1.60, -- Mad King
    npc_dota_hero_queenofpain       = 2.00, -- Purifier
    npc_dota_hero_phantom_assassin  = 2.60, -- Noble Shadow
    npc_dota_hero_spirit_breaker    = 2.40, -- Shepherd
    npc_dota_hero_slark             = 2.60, -- Whale Hunter
}
level_armour_application_ratios = {
	npc_dota_hero_axe 				= 3.40, -- Warden
	npc_dota_hero_crystal_maiden  	= 3.10, -- Winter's Bride
	npc_dota_hero_earth_spirit 		= 2.80, -- Sculptor
	npc_dota_hero_templar_assassin 	= 3.00, -- Merchant Princess
    npc_dota_hero_naga_siren        = 3.10, -- The Typhoon
    npc_dota_hero_skeleton_king     = 3.00, -- Warlock Knight
    npc_dota_hero_rattletrap        = 3.30, -- Ancient Babysitter
    npc_dota_hero_spectre           = 2.90, -- Art Prodigy
    npc_dota_hero_legion_commander  = 3.00, -- High Huntress
    npc_dota_hero_lycan             = 3.10, -- The Alpha
    npc_dota_hero_bloodseeker       = 3.10, -- Survivor
    npc_dota_hero_undying           = 3.10, -- Rotting Tomb
    npc_dota_hero_pudge             = 3.10, -- Desert Raider
    npc_dota_hero_vengefulspirit    = 3.10, -- Elegant Dancer
    npc_dota_hero_beastmaster       = 3.40, -- Enforcer
    npc_dota_hero_meepo             = 2.90, -- Tangled Dreamer
    npc_dota_hero_oracle            = 3.10, -- Loremaster
    npc_dota_hero_life_stealer      = 3.00, -- Flesh
    npc_dota_hero_ember_spirit      = 3.10, -- Pyrebug
    npc_dota_hero_invoker           = 3.10, -- Mad King
    npc_dota_hero_queenofpain       = 2.90, -- Purifier
    npc_dota_hero_phantom_assassin  = 3.30, -- Noble Shadow
    npc_dota_hero_spirit_breaker    = 3.10, -- Shepherd
    npc_dota_hero_slark             = 3.30, -- Whale Hunter
}
level_magic_resistance_application_ratios = {
	npc_dota_hero_axe 				= 1.00, -- Warden
	npc_dota_hero_crystal_maiden  	= 0.00, -- Winter's Bride
	npc_dota_hero_earth_spirit 		= 1.00, -- Sculptor
	npc_dota_hero_templar_assassin 	= 0.00, -- Merchant Princess
    npc_dota_hero_naga_siren        = 0.00, -- The Typhoon
    npc_dota_hero_skeleton_king     = 1.00, -- Warlock Knight
    npc_dota_hero_rattletrap        = 1.00, -- Ancient Babysitter
    npc_dota_hero_spectre           = 0.00, -- Art Prodigy
    npc_dota_hero_legion_commander  = 0.00, -- High Huntress
    npc_dota_hero_lycan             = 0.00, -- The Alpha
    npc_dota_hero_bloodseeker       = 1.25, -- Survivor
    npc_dota_hero_undying           = 1.00, -- Rotting Tomb
    npc_dota_hero_pudge             = 1.00, -- Desert Raider
    npc_dota_hero_vengefulspirit    = 0.00, -- Elegant Dancer
    npc_dota_hero_beastmaster       = 1.00, -- Enforcer
    npc_dota_hero_meepo             = 0.00, -- Tangled Dreamer
    npc_dota_hero_oracle            = 0.00, -- Loremaster
    npc_dota_hero_life_stealer      = 0.00, -- Flesh
    npc_dota_hero_ember_spirit      = 0.00, -- Pyrebug
    npc_dota_hero_invoker           = 0.00, -- Mad King
    npc_dota_hero_queenofpain       = 0.00, -- Purifier
    npc_dota_hero_phantom_assassin  = 1.00, -- Noble Shadow
    npc_dota_hero_spirit_breaker    = 1.00, -- Shepherd
    npc_dota_hero_slark             = 1.00, -- Whale Hunter
}
initial_armour_application_ratios = {
	npc_dota_hero_axe 				= 19.0, -- Warden
	npc_dota_hero_crystal_maiden  	= 15.0, -- Winter's Bride
	npc_dota_hero_earth_spirit 		= 20.0, -- Sculptor
	npc_dota_hero_templar_assassin 	= 16.0, -- Merchant Princess
    npc_dota_hero_naga_siren        = 15.0, -- The Typhoon
    npc_dota_hero_skeleton_king     = 21.0, -- Warlock Knight
    npc_dota_hero_rattletrap        = 19.5, -- Ancient Babysitter
    npc_dota_hero_spectre           = 10.0, -- Art Prodigy
    npc_dota_hero_legion_commander  = 16.0, -- High Huntress
    npc_dota_hero_lycan             = 15.0, -- The Alpha
    npc_dota_hero_bloodseeker       = 19.0, -- Survivor
    npc_dota_hero_undying           = 20.0, -- Rotting Tomb
    npc_dota_hero_pudge             = 20.0, -- Desert Raider
    npc_dota_hero_vengefulspirit    = 15.0, -- Elegant Dancer
    npc_dota_hero_beastmaster       = 19.0, -- Enforcer
    npc_dota_hero_meepo             = 10.0, -- Tangled Dreamer
    npc_dota_hero_oracle            = 15.0, -- Loremaster
    npc_dota_hero_life_stealer      = 16.0, -- Flesh
    npc_dota_hero_ember_spirit      = 15.0, -- Pyrebug
    npc_dota_hero_invoker           = 15.0, -- Mad King
    npc_dota_hero_queenofpain       = 10.0, -- Purifier
    npc_dota_hero_phantom_assassin  = 19.0, -- Noble Shadow
    npc_dota_hero_spirit_breaker    = 20.0, -- Shepherd
    npc_dota_hero_slark             = 19.0, -- Whale Hunter
}
initial_magic_resistance_application_ratios = {
	npc_dota_hero_axe 				= 33.0, -- Warden
	npc_dota_hero_crystal_maiden  	= 33.0, -- Winter's Bride
	npc_dota_hero_earth_spirit 		= 33.0, -- Sculptor
	npc_dota_hero_templar_assassin 	= 33.0, -- Merchant Princess
    npc_dota_hero_naga_siren        = 33.0, -- The Typhoon
    npc_dota_hero_skeleton_king     = 33.0, -- Warlock Knight
    npc_dota_hero_rattletrap        = 33.0, -- Ancient Babysitter
    npc_dota_hero_spectre           = 33.0, -- Art Prodigy
    npc_dota_hero_legion_commander  = 33.0, -- High Huntress
    npc_dota_hero_lycan             = 33.0, -- The Alpha
    npc_dota_hero_bloodseeker       = 33.0, -- Survivor
    npc_dota_hero_undying           = 33.0, -- Rotting Tomb
    npc_dota_hero_pudge             = 33.0, -- Desert Raider
    npc_dota_hero_vengefulspirit    = 33.0, -- Elegant Dancer
    npc_dota_hero_beastmaster       = 33.0, -- Enforcer
    npc_dota_hero_meepo             = 33.0, -- Tangled Dreamer
    npc_dota_hero_oracle            = 33.0, -- Loremaster
    npc_dota_hero_life_stealer      = 33.0, -- Flesh
    npc_dota_hero_ember_spirit      = 33.0, -- Pyrebug
    npc_dota_hero_invoker           = 33.0, -- Mad King
    npc_dota_hero_queenofpain       = 33.0, -- Purifier
    npc_dota_hero_phantom_assassin  = 33.0, -- Noble Shadow
    npc_dota_hero_spirit_breaker    = 33.0, -- Shepherd
    npc_dota_hero_slark             = 33.0, -- Whale Hunter
}